# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_squashed_0002_auto_20170809_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='breakpoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(40, 30, 20, 10, 5), size=None),
            preserve_default=False,
        ),
    ]
