# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_city_breakpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='breakpoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5),
        ),
    ]
