# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170829_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakpoints', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=5)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
