# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170829_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='colors',
            new_name='map_colors',
        ),
    ]
