# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170830_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_page_explainer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='analysis_page_explainer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='data_page_explainer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
