# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_squashed_0011_auto_20170809_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ediimages',
            name='overlay_text',
            field=models.CharField(max_length=255),
        ),
    ]
