# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_cityaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slugged_name',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
