# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170809_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutpagefiles',
            name='page',
        ),
        migrations.RemoveField(
            model_name='analysispagecontent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='analysispagefiles',
            name='page',
        ),
        migrations.RemoveField(
            model_name='mappagecontent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='mapspagedata',
            name='page',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='AboutPageContent',
        ),
        migrations.DeleteModel(
            name='AboutPageFiles',
        ),
        migrations.DeleteModel(
            name='AnalysisPage',
        ),
        migrations.DeleteModel(
            name='AnalysisPageContent',
        ),
        migrations.DeleteModel(
            name='AnalysisPageFiles',
        ),
        migrations.DeleteModel(
            name='MapPageContent',
        ),
        migrations.DeleteModel(
            name='MapsPage',
        ),
        migrations.DeleteModel(
            name='MapsPageData',
        ),
    ]
